name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: Run Specific Job
        type: boolean
        required: false
      custom_message:
        description: Enter a custom message
        type: string
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.run_job }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo ${{ inputs.custom_message }}
  